### PR TITLE
chore: :arrow_up: upgrade all dependencies

### PR DESCRIPTION
**Pull request by alphainfinitus**
Upgrades node version to LTS and all dependencies to latest using yarn.
Fixes build errors.

### CODE REVIEW

**Review by hoonsubin — CHANGES_REQUESTED** [review]
This PR https://github.com/TeamSTEP/slack-in-your-time/pull/54 should update the node version to the latest stable for the workflow.

Please update the PR (note that there is an issue with the Jest ESM config, that should also be updated)

**Comment by alphainfinitus** [comment]
Hi @hoonsubin, the PR has been updated. Please give it a look. Thanks!

**Comment by alphainfinitus** [comment]
@hoonsubin , I've fixed the CI build. The unit test now runs successfully.
The unit test will fail due to semantic errors in the test, i believe.

**Comment by hoonsubin** [comment]
> @hoonsubin , I've fixed the CI build. The unit test now runs successfully. The unit test will fail due to logical errors in the test due to semantic errors in the test, i believe.

I see! I'll give it one more check and get back to you

**Review by hoonsubin — APPROVED** [review]
LGTM

**Pull request merged**
